Ecommerce/urls.py
from django.contrib import admin
from django.conf.urls import url,include

urlpatterns = [
    url('admin/', admin.site.urls),
    url('accounts/', include('allauth.urls')),
    url('', include('store.urls')),
    
]

store/urls.py
from django.urls import path
from .views import (
    ProductDetailView,
    CheckoutView,
    cart,
    StoreView,add_to_cart,remove_from_cart,OrderSummaryView,remove_single_item_from_cart,Payment
)

app_name='store'

urlpatterns=[
    path('', StoreView.as_view() ,name='store'),
    # path('cart', cart, name='cart'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order-summary/', OrderSummaryView.as_view(), name='cart'),
    path('product/<slug>/',ProductDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>', add_to_cart , name='add_to_cart'),
    path('remove-from-cart/<slug>', remove_from_cart , name='remove_from_cart'),
    path('remove-item-from-cart/<slug>', remove_single_item_from_cart , name='remove_single_item_from_cart'),
    path('payment/<payment_option>', Payment.as_view(), name='payment')    
]

store/models.py
from django.conf import settings
from django.db import models
from django.shortcuts import reverse
from django_countries.fields import CountryField


import stripe
stripe.api_key = settings.STRIPE_SECRET_KEY
# Create your models here.

CATEGORY_CHOICE=(
    ('S','Shirt'),
    ('SH','Shoe'),
    ('SW','Sport wear'),
    ('OW','Outwear')
)

CATEGORY_LABEL=(
    ('P','primary'),
    ('S','secondary'),
    ('D','danger')
)

#items that can be purchased
class Item(models.Model):
    
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICE, max_length=2)
    label = models.CharField(choices=CATEGORY_LABEL, max_length=2)
    slug = models.SlugField()
    description = models.TextField()
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('store:product', kwargs={
            'slug': self.slug
        })
        
    def get_add_to_cart_url(self):
        return reverse('store:add_to_cart', kwargs={
            'slug': self.slug
        })
    
    def remove_from_cart_url(self):
        return reverse('store:remove_from_cart', kwargs={
            'slug':self.slug
        })

#items in the cart
class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE , blank=True ,null=True)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    
     
    def __str__(self):
        return f"{self.quantity} of {self.item.title}"
    
    def get_total_item_price(self):
        return self.quantity * self.item.price
    
    def get_total_discount_price(self):
        return self.quantity * self.item.discount_price
    
    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_price()

    def get_final_amount(self):
        if self.item.discount_price:
            return self.get_total_discount_price()
        return self.get_total_item_price()
            
#cart
class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    billing_address = models.ForeignKey('BillingAddress', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey('Payment', on_delete=models.SET_NULL, blank=True, null=True)
    
    def __str__(self):
        return self.user.username
    
    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_amount()
        return total
    

class BillingAddress(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip =models.CharField(max_length=100) 
    def __str__(self):
        return self.user.username
   
   
class userStripe(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL)
    stripe_id = models.CharField(max_length=200, null=True, blank=True)

    def __unicode__(self):
        if self.stripe_id:
            return str(self.stripe_id)
        else:
            return self.user.username 
        
 
class Payment(models.Model):
     stripe_charge_id = models.CharField(max_length=50)
     user=models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, blank=True, null=True)
     amount = models.FloatField()
     timestamp = models.DateField(auto_now=True)
     
     def __str__(self):
         return self.user.username
     
    

store/forms.py
from django import forms
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget

PAYMENT_CHOICES = (
    ('S', 'Stripe'),
    ('P', 'Paypal')
)

class CheckoutForm(forms.Form):
    street_address= forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'237 Thika'
    }))
    apartment_address = forms.CharField(required=False, widget=forms.TextInput(attrs={
        'placeholder':'Appartment or suit',
        'id':'address-2'
    }))
    country = CountryField(blank_label='(select)').formfield(widget=CountrySelectWidget(attrs={
        'class':'form-field form-control custom-select w-50'
    }))
    zip = forms.CharField(widget=forms.TextInput(attrs={
        'class':'form-field form-control',
        'id':'zip'
    }))
    same_shipping_address= forms.BooleanField(widget=forms.CheckboxInput())
    save_info = forms.BooleanField(widget=forms.CheckboxInput())
    payment_option = forms.ChoiceField(widget=forms.RadioSelect, choices=PAYMENT_CHOICES)

store/views.py
from django.conf import settings
from django.shortcuts import render,get_object_or_404,redirect
from django.views.generic import ListView, DetailView,View
from django.utils import timezone
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Item, OrderItem ,Order, BillingAddress
from .forms import CheckoutForm
# Create your views here.

import stripe
stripe.api_key = settings.STRIPE_SECRET_KEY


class StoreView(ListView):
    model=Item
    template_name="store/store.html"


class OrderSummaryView(LoginRequiredMixin,View):
    def get(self, *args, **kwargs):
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            
            context={
                'object':order
            }
            
            return render(self.request, 'store/cart.html', context)
        except ObjectDoesNotExist:
            messages.error(self.request, "You dont have an active order")
            return redirect("/")

def product(request):
    context={}
    return render(request,'store/product.html',context)

class ProductDetailView(DetailView):
    model=Item
    template_name='store/product.html'

def cart(request):
    context={}
    return render(request, 'store/cart.html', context)

class CheckoutView(View):
    def get(self, *args, **kwargs):
        form = CheckoutForm()
        template_name = 'store/checkout.html'
        context = {
            'form': form
        }
        return render(self.request, template_name , context)

    def post(self, *args, **kwargs):
        form = CheckoutForm(self.request.POST or None)
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            if form.is_valid():
                street_address=form.cleaned_data.get('street_address')
                apartment_address=form.cleaned_data.get('apartment_address')
                country=form.cleaned_data.get('country')
                zip=form.cleaned_data.get('zip')
                #TODO: add functionality for these fields
                # same_shipping_address=form.cleaned_data.get('same_billing_address')
                # save_info=form.cleaned_data.get('save_info')
                payment_option=form.cleaned_data.get('payment_option')
                billing_address = BillingAddress(
                    user=self.request.user,
                    street_address=street_address,
                    apartment_address=apartment_address,
                    country=country,
                    zip=zip
                )
                billing_address.save()
                order.billing_address = billing_address
                order.save()
                # TODO: add redirect to the selected payment option
                
                if payment_option == 'S':
                    return redirect('store:payment', payment_option="stripe")
                elif payment_option == 'P':
                    return redirect('store:payment', payment_option='paypal')
                else:
                    messages.warning(self.request, " Invalid payment option")
                    return redirect("store:checkout")
            
        except ObjectDoesNotExist:
            messages.error(self.request, "You do not have an active order")
            return redirect('store:checkout')
        
class Payment(View):
    def payment(self,request):
        publishkey = settings.STRIPE_PUBLISHABLE_KEY
        print(request.user.userStripe.stripe_id)
    def get(self, *args, **kwargs):
        order = Order.objects.get(user=self.request.user, ordered=False)
        context = {
            'order':order
        }
        template_name = 'store/payment.html'
        return render(self.request, template_name, context)
    
    def post(self, *args, **kwargs):
        order = Order.objects.get(user=self.request.user, ordered=False)
        token = self.request.POST.get('stripToken')
        amount = int(order.get_total() *100)
        
    
        try:
            charge=stripe.Charge.create(
                amount = amount, #cents
                currency = "ksh", 
                source=token, #obtained with strip.js
            )
            #create payment
            payment = Payment()
            payment.stripe_charge_id = charge['id']
            payment.user = self.request.user
            payment.amount = order.get_total()
            payment.save()
        
         
            #assign payment
            order.ordered = True
            order.payment = payment
            order.save()

            messages.success(self.request, "Your order was successful")
            return redirect("/")
            
        except stripe.error.CardError as e:
            # Since it's a decline, stripe.error.CardError will be caught
            body = e.json_body
            err = body.get('error',{})
            messages.error(self.request, f"{err.get('message')}")
        except stripe.error.RateLimitError as e:
            # Too many requests made to the API too quickly
            messages.error(self.request, "Rate limit error")
            return redirect("/")
            

        except stripe.error.InvalidRequestError as e:
            # Invalid parameters were supplied to Stripe's API
            messages.error(self.request, "Invalid parameters")
            return redirect("/")


        except stripe.error.AuthenticationError as e:
            # Authentication with Stripe's API failed
            # (maybe you changed API keys recently)
            messages.error(self.request, "Not authenticated")
            return redirect("/")

        except stripe.error.APIConnectionError as e:
            # Network communication with Stripe failed
            messages.error(self.request, "Network error")
            return redirect("/")

        except stripe.error.StripeError as e:
            # Display a very generic error to the user, and maybe send
            # yourself an email
            messages.error(self.request, "Something went wrong. You were not charged. Please try again.")
            return redirect("/")

        except Exception as e:
            #send email to ourselves
            messages.error(self.request, "Serious error occurred. We have been notified.")
            return redirect("/")

       

@login_required
def add_to_cart(request, slug):
    item = get_object_or_404(Item, slug=slug)
    order_item, created = OrderItem.objects.get_or_create(item=item,
                                                 user=request.user, 
                                                 ordered=False
                                                 )
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        # check if the order item is in the order
        if order.items.filter(item__slug=item.slug).exists():
            order_item.quantity += 1 
            order_item.save()
            messages.info(request, "Item quantity was updated") 
            return redirect ("store:cart")
            
        else:
            messages.info(request, "Item was added to cart")
            order.items.add(order_item)
            return redirect ("store:cart")
            
    else:
        ordered_date = timezone.now()
        order=Order.objects.create(user=request.user, ordered_date=ordered_date)
        order.items.add(order_item)
        messages.info(request, "Item was added to cart")
        
    return redirect ("store:product")

@login_required
def remove_from_cart(request, slug):
    item=get_object_or_404(Item, slug=slug)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        # check if the order item is in the order
        if order.items.filter(item__slug=item.slug).exists():
            order_item= OrderItem.objects.filter(
                item=item,
                user=request.user, 
                ordered=False
            )[0]
            order.items.remove(order_item)
            messages.info(request, "Item was removed from your cart")
            return redirect ("store:cart")

        else:
            # add message saying order doesnt contain the item
            messages.info(request, "order does not contain the item")
            return redirect ("store:product", slug=slug)
            
    else:
        # add message saying user doesnt have an order
        messages.info(request, "You do not have an order")
        return redirect ("store:product", slug=slug)
    return redirect ("store:product", slug=slug)
            
@login_required
def remove_single_item_from_cart(request, slug):
    item=get_object_or_404(Item, slug=slug)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        # check if the order item is in the order
        if order.items.filter(item__slug=item.slug).exists():
            order_item= OrderItem.objects.filter(
                item=item,
                user=request.user, 
                ordered=False
            )[0]
            if order_item.quantity >1:
                order_item.quantity -= 1
                order_item.save()
            else:
                order.items.remove(order_item)
            messages.info(request, "Item quantity was updated")
            return redirect('store:cart')

        else:
            # add message saying order doesnt contain the item
            messages.info(request, "order doesnt contain the item")
            return redirect ("store:product", slug=slug)
            
    else:
        # add message saying user doesnt have an order
        messages.info(request, "You do not have an order")
        return redirect ("store:product", slug=slug)
    return redirect ("store:product", slug=slug)

store/templates/store/base.html
<!DOCTYPE html>
{% load cart_template_tags %}
{% load static %}
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" charset="UTF-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block head_title %}{% endblock %}</title>
  {% block extra_head %}
  {% endblock %}
  
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <!-- owl carousel CDN-->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" integrity="sha256-UhQQ4fxEeABh4JrcmAJ1+16id/1dnlOEVCFOxDef9Lw=" crossorigin="anonymous" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css" integrity="sha256-kksNxjDRxd/5+jGurZUJd1sdR2v+ClrCl3svESBaJqw=" crossorigin="anonymous" />

  <!-- font awesome icons -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.1/css/all.min.css" integrity="sha256-2XFplPlrFClt0bIdPgpz8H7ojnk10H69xRqd9+uTShA=" crossorigin="anonymous" />
    
</head>
<body>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark justify-content-between">
      <a class="navbar-brand font-rubic" href="{% url 'store:store' %}">Ecom</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav m-auto font-rubik">
          {% for category in object_list %}
          <li class="nav-item active">
            <a class="nav-link" href="#">{{category.get_category_display}} <span class="sr-only">(current)</span></a>
          </li>
          {% endfor %}
          <!-- <li class="nav-item">
            <a class="nav-link" href="#">Category</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Products <i class="fas fa-chevron-down"></i></a>
              
          <li>
          <li class="nav-item">
              <a class="nav-link" href="#">Blog</a>
          </li>
          <li class="nav-item">
              <a class="nav-link" href="#">Category <i class="fas fa-chevron-down"></i></a>
          </li> -->
          
        </ul>

          <div class="form-inline my-2 my-lg-0">
            {% if request.user.is_authenticated %}

              <a class="nav-link waves-effect" href="{% url 'store:cart' %}">
                <i class="fas fa-shopping-cart color-yellow"></i>
                <span class="clear-fx d-none d-sm-inline-block color-yellow">Cart</span>
                <span class="badge red z-depth mr-1 color-yellow">{{ request.user|cart_item_count }}</span>
              </a>
              <a class="nav-link waves-effect" href="{% url 'account_logout' %}">
                <span class="clear-fx d-none d-sm-inline-block color-white">Logout</span>
              </a>
            {% else %}
          
              <a class="nav-link waves-effect" href="{% url 'account_login' %}">
                <span class="clear-fx d-none d-sm-inline-block color-white">Login</span>
              </a>
              <a class="nav-link waves-effect" href="{% url 'account_signup' %}">
                <span class="clear-fx d-none d-sm-inline-block color-white">Signup</span>
              </a>

            {% endif %}
          </div>
      </div>

      
  </nav>

  <div class="pt-1">
    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
          {{message}}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      {% endfor %}
    {% endif %}
  </div>

  <div class="container">
    <br>
    {% block content %}
    {% endblock content %}


    {% block extra_body %}
    {% endblock %}
  </div>

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

  <!-- owl carousel js-->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js" integrity="sha256-pTxD+DSzIwmwhOqTFN+DB+nHjO4iAsbgfyFq5K5bcE0=" crossorigin="anonymous"></script>
  <script src="{% static 'js/index.js' %}"></script>


</body>
</html>

<!-- python manage.py sass static/sass/style.scss static/css/style.css --watch -->

store/templates/store/cart.html
{% extends 'store/base.html' %}
{%load static%}
{% block content %}
<div class="row">
    <div class="container">
        <div class="col-lg-12">
            <div class="box-element">
                {% if object.get_total%}
                    <a class="btn btn-outline-dark" href="{% url 'store:store' %}">&#x2190; Continue Shopping</a>
                    <a style="float: right; margin: 5px;" class="btn btn-warning" href="{% url 'store:checkout' %}">Proceed to Checkout</a>
                    <br>
                    <hr>
                    <span><h5 class="float-right">Total:<strong>Ksh.{{object.get_total}}</strong></h5></span>
                {% endif %}
                <br>
                <br>
                    {% for order_item in object.items.all %}

                
            </div>
            <br>
            
            <div class="box-element">
                <div class="cart-row d-flex container-fluid">
                    <!-- <div class="mobile" style="flex:1"></div>
                    <div class="mobile" style="flex:1"></div>-->
                    <div class="desktop" style="flex:1"></div>
                    <div style="flex:2"><strong>Item</strong></div>
                    <div class="mobile" style="flex:2"><strong>Price</strong></div>
                    <div style="flex:2.5"><strong>Quantity</strong></div>
                    <div style="flex:2"><strong>Total Item Price</strong></div>
                    <div class="desktop" style="flex:1"></div>

                </div>

                <div class="cart-row d-flex container-fluid">
                        <div class="mobile" style="flex:1"><h5><strong>{{forloop.counter}}</strong></h5></div>
                        <!-- <div class="mobile"style="flex:1"><img class="row-image" src="{% static 'images/640.png' %}"></div> -->
                        <div style="flex:2" class="title"><p>{{order_item.item.title}}</p></div>
                        <div class="mobile" style="flex:2"><p>{{order_item.item.price}}</p></div>
                        <div style="flex:2.5">
                            <div class="form-field">
                                <table>
                                    <td>
                                        <a href="{% url 'store:remove_single_item_from_cart' order_item.item.slug%}"><i class="fas fa-chevron-down pr-3"></i></a>
                                        {{order_item.quantity}}
                                        <a href="{% url 'store:add_to_cart' order_item.item.slug%}"><i class="fas fa-chevron-up pl-3"></i></a>
                                    </td>
                                </table>
                                <!-- <input class="quantity" disabled value="{{order_item.quantity}}"><i class="fas fa-chevron-up"></i> -->
                            </div> 
                        </div>
                    
                    <div style="flex: 2;" class="price">
                        {% if order_item.item.discount_price %}
                            Ksh.{{order_item.get_total_discount_price}}
                            <div><strong class="badge badge-warning">Saving {{order_item.get_amount_saved}}</strong></div>
                        {% else %}
                            Ksh.{{order_item.get_total_item_price}}
                        {% endif %}
                    </div>
                    <div">
                        <a href="{% url 'store:remove_from_cart' order_item.item.slug %}"><i style="float: right;color: red;" class="fas fa-trash"></i></a>
                    </div>
                    
                    <div>
                    {% empty %}
                    <div class="row">
                        <!-- <div class="col-md-3"></div> -->
                        <div class="col-md-12">
                            <a class="btn btn-outline-dark" href="{% url 'store:store' %}">&#x2190; Continue Shopping</a>
                            <a style="float: right;color: black;" class="px-5 font-baloo color-secondary-bg">Your cart is empty.</a>
                            
                        </div>
                        <!-- <div class="col-md-3"></div> -->
                    </div>
                    {% endfor %}
                </div>
            </div>
            
        </div>
    </div>
</div>
{% endblock content %}

store/templates/store/order_summary.html
{% extends 'store/base.html' %}
{% load static %}
{% block content %}

<div class="container">
    <div class="table-responsive text-nowrap">
        <h2 class="font-rubik">Order Summary</h2>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Item</th>
                    <th scope="col">Price</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Total-Item-Price</th>
                </tr>
            </thead>
            <tbody>
                {% for order_item in object.items.all %}
                <tr>
                    <th scope="row">1</th>
                    <td>{{order_item.item.title}}</td>
                    <td>{{order_item.item.price}}</td>
                    <td>{{order_item.quantity}}</td>
                    <td>
                        {% if order_item.item.discount_price %}
                            Ksh.{{order_item.get_total_discount_price}}
                            <strong class="badge badge-warning">Saving {{order_item.get_amount_saved}}</strong>
                        {% else %}
                            Ksh.{{order_item.get_total_item_price}}
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>


{% endblock content %}

store/templates/store/store.html
{% extends 'store/base.html' %}
{% load static %}
{% block content %}

<div class="row">
    {% for item in object_list %}
    <div class="col-lg-4">
        <a href="{{ item.get_absolute_url }}"><img class="thumbnail" src="{% static 'images/air-jordan.webp' %}" alt="product1"></a>
        
        <div class="box-element product">
            <a href="" class="grey-text d-flex m-0">
            <h5 class="text-center">{{item.get_category_display}}</h5>
            </a>
            <span class="badge badge-pill color-yellow-bg float-right ">{{item.get_label_display}}</span>

            <h6><strong>{{item.title}}</strong></h6>
            <hr>
            
            <!-- <button class="btn btn-outline-secondary add-btn">Add to cart</button> -->
            <a class="btn btn-outline-success" href="{{ item.get_absolute_url }}">View</a>
            <h4 style="float:right;"><strong>Ksh.
                {% if item.discount_price %}
                {{item.discount_price}}
                {% else %}
                {{item.price}}
                {% endif %}
            </strong></h4>
        </div>
    </div>
    {% endfor%}
</div>


{% endblock content %}